writed factorial function
js-tasks-ru/jsbasic-20201214_nikolay-makarevich pull request #2
Opened 2020-12-05 19:42 UTC by NMakarevich

Написана функция нахождения факториала числа n с помощью цикла while. Вариант с циклом for тоже был отработан.

2020-12-05 19:55 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 0 равен 1
+ факториал 3 равен 6 
+ факториал 5 равен 120 
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-05 21:09 UTC, SinimaWath requested changes

2020-12-05 21:09 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  };
После {} блоков, не нужно ставить ;

2020-12-05 21:09 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  let result = 1;
В твоем случае, разумнее будет унести обьявление переменной, под блок проверки `if ()`. Это будет понятней, так как используешь эту переменную, только после проверки.

2020-12-05 21:09 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  if (n === 0) {
Для n === 1, тоже стоит в таком случае возвращать 1

2020-12-06 18:00 UTC, NMakarevich commented on 1-module/1-task/index.js
> +  };
Понял. Спасибо.

2020-12-06 18:03 UTC, NMakarevich commented on 1-module/1-task/index.js
> +  let result = 1;
Перенес объявление переменной. Функция не работает при n = 0 - Cannot access 'result' before initialization

2020-12-06 18:18 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 0 равен 1
+ факториал 5 равен 120 
+ факториал 3 равен 6 
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-06 18:24 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  let result = 1;
Смотри, когда ты заранее знаешь результат функции при n === 0 и 1. Тебе нет необходимости создавать переменную, нужно сразу возвращать значение. В твоем случае, можно сразу вернуть 1

2020-12-06 18:35 UTC, NMakarevich commented on 1-module/1-task/index.js
> +  let result = 1;
Понял. Нужно было заменить `return resuslt;` на `return 1;`. Спасибо.

2020-12-06 19:13 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  let result = 1;
Да все верно

2020-12-06 19:14 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  if (n) {
На будущее: такой стиль написания кода, меньше приветствуется, так сильно увеличивается вложенность.

Правильней было бы:
```
if (!n) {
   return;
}
// ... остальной код
```

В таком случае, вложенность остается равна 1

2020-12-06 19:54 UTC, NMakarevich commented on 1-module/1-task/index.js
> +  if (n) {
Сначала написал как Вы предлагаете, но захотел убрать лишний return и переписал так. В дальнейшем учту. Спасибо.

2020-12-06 19:56 UTC, NMakarevich commented on 1-module/1-task/index.js
> +  if (n) {
Устранить данный недочёт в этой задаче или оставить как есть?

2020-12-06 20:03 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  if (n) {
Устрани лучше в этой задаче.

2020-12-07 18:38 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Вычислить факториал
+ факториал 0 равен 1
+ факториал 1 равен 1
+ факториал 3 равен 6 
+ факториал 5 равен 120 
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-07 18:59 UTC, SinimaWath approved these changes

2020-12-07 18:59 UTC, merged