Module 4
js-tasks-ru/jsbasic-20201214_nikolay-makarevich pull request #6
Opened 2020-12-26 17:40 UTC by NMakarevich

All tasks from module 4 are done.

2020-12-26 17:49 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция highlight
+ Проставит класс male/female, в зависимости от содержимого ячекйки Gender
+ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
+ Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
+ Проставит аттрибут hidden, если  data-available атрибута нет вообще
```
```diff
Функция makeFriendsList(friends)
+ проверяем содержимое списка
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
+ функция должна возвращать HTML список
```
```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку пятой строки в красный
+ должна окрашивать ячейку первой строки в красный
+ должна окрашивать ячейку четвёртой строки в красный
+ должна окрашивать ячейку третьей строки в красный
+ должна окрашивать ячейку второй строки в красный
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-29 15:10 UTC, SinimaWath requested changes

2020-12-29 15:10 UTC, SinimaWath commented on 4-module/1-task/index.js
> +    uList.appendChild(listItem);
Давай попробуем переписать на шаблон:
1. Сделать функцию: friendTemplate({...});
2. Эта функция возвращает шаблон.
3. Этот шаблон потом вставляешь

Обычно это проще поддерживать, чем createElement. Или в крайнем случае делать отдельную функцию, которая составляет компонент через createElement

2020-12-29 15:10 UTC, SinimaWath commented on 4-module/2-task/index.js
> +    const rows = table.getElementsByTagName("tr");
Лучше использовать querySelector

2020-12-29 15:10 UTC, SinimaWath commented on 4-module/2-task/index.js
> +    }
Давай forEach

2020-12-29 15:10 UTC, SinimaWath commented on 4-module/3-task/index.js
> +        }
Давай сделаем отдельную функцию на каждый атрибут:
```
for (...) {
  setAvailableIfCan(el, statusCell);
  setGenderIfCan(el, genderCell);
  setTextDecoration(el, ageCell);
}
```

Так будет проще поддерживать

2020-12-29 15:10 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    for (let i = 0; i < rows.length; i++) {
Давай forEach ;)

2020-12-29 17:03 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция highlight
+ Проставит класс male/female, в зависимости от содержимого ячекйки Gender
+ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
+ Проставит аттрибут hidden, если  data-available атрибута нет вообще
+ Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
```
```diff
Функция makeFriendsList(friends)
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
+ функция должна возвращать HTML список
+ проверяем содержимое списка
```
```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку пятой строки в красный
+ должна окрашивать ячейку четвёртой строки в красный
+ должна окрашивать ячейку второй строки в красный
+ должна окрашивать ячейку третьей строки в красный
+ должна окрашивать ячейку первой строки в красный
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-29 20:46 UTC, SinimaWath approved these changes

2020-12-29 20:46 UTC, merged